import "./globals.css";
import Navbar from "../components/UI/Navbar";
import Footer from "../components/UI/Footer";
import FollowCursor from "../components/features/FollowCursor";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
  title: "IMMM Finances",
  description: "Generated by Next.js",
  icons: {
    icon: "/public/favicon.svg", // Hier wird auf die Favicon-Datei verwiesen
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body>
        <main className="min-h-screen bg-white">
          <Navbar />
          {/* <FollowCursor /> */}
          <div className="w-full">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
