import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "../components/UI/Navbar";
import Footer from "../components/UI/Footer";
import FollowCursor from "../components/features/FollowCursor";

// Konfiguriere die Schriftart mit einer CSS-Variable
const urbanist = Urbanist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-urbanist", // 1. Definiere den Namen der CSS-Variable
  weight: "variable", // <-- hier bestimmst du die weights
});

export const metadata = {
  title: "IMMM Finances",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de" className={`${urbanist.variable} ${urbanist.className}`}>
      <body>
        <main className="min-h-screen bg-white">
          <Navbar />
          {/* <FollowCursor /> */}
          <div className="w-full">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
